// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using task_01_ef_core_modeling_drills.Data;

#nullable disable

namespace task_01_ef_core_modeling_drills.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260918232303_Drill 8")]
    partial class Drill8
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("task_01_ef_core_modeling_drills.Entities.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<float>("FinalGrade")
                        .HasColumnType("real");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TrackId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("TrackId");

                    b.ToTable("Enrollments");

                    b.HasData(
                        new
                        {
                            Id = new Guid("66666666-6666-6666-6666-666666666666"),
                            EnrollmentDate = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalGrade = 88.5f,
                            StudentId = new Guid("11111111-1111-1111-1111-111111111111"),
                            TrackId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("77777777-7777-7777-7777-777777777777"),
                            EnrollmentDate = new DateTime(2026, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalGrade = 92f,
                            StudentId = new Guid("22222222-2222-2222-2222-222222222222"),
                            TrackId = new Guid("33333333-3333-3333-3333-333333333333")
                        },
                        new
                        {
                            Id = new Guid("88888888-8888-8888-8888-888888888888"),
                            EnrollmentDate = new DateTime(2026, 9, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalGrade = 76.5f,
                            StudentId = new Guid("33333333-3333-3333-3333-333333333333"),
                            TrackId = new Guid("44444444-4444-4444-4444-444444444444")
                        },
                        new
                        {
                            Id = new Guid("99999999-9999-9999-9999-999999999999"),
                            EnrollmentDate = new DateTime(2026, 9, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalGrade = 95f,
                            StudentId = new Guid("44444444-4444-4444-4444-444444444444"),
                            TrackId = new Guid("55555555-5555-5555-5555-555555555555")
                        },
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            EnrollmentDate = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalGrade = 81f,
                            StudentId = new Guid("55555555-5555-5555-5555-555555555555"),
                            TrackId = new Guid("33333333-3333-3333-3333-333333333333")
                        });
                });

            modelBuilder.Entity("task_01_ef_core_modeling_drills.Entities.Instructor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Instructors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Fullname = "Ahmed Hassan"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Fullname = "Mariam Ibrahim"
                        });
                });

            modelBuilder.Entity("task_01_ef_core_modeling_drills.Entities.PaymentSummary", b =>
                {
                    b.Property<Guid>("EnrollmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPaid")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalRequired")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("EnrollmentId");

                    b.ToTable("PaymentSummaries");
                });

            modelBuilder.Entity("task_01_ef_core_modeling_drills.Entities.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fullname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "omar.hassan@example.com",
                            Fullname = "Omar Hassan",
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "youssef.ahmed@example.com",
                            Fullname = "Youssef Ahmed",
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "karim.mahmoud@example.com",
                            Fullname = "Karim Mahmoud",
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "mariam.adel@example.com",
                            Fullname = "Mariam Adel",
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            CreatedAt = new DateTime(2026, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nour.khaled@example.com",
                            Fullname = "Nour Khaled",
                            IsActive = true,
                            IsDeleted = false,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("task_01_ef_core_modeling_drills.Entities.StudentProfile", b =>
                {
                    b.Property<Guid>("StudentID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmergencyPhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalId")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)");

                    b.HasKey("StudentID");

                    b.ToTable("StudentProfiles");

                    b.HasData(
                        new
                        {
                            StudentID = new Guid("11111111-1111-1111-1111-111111111111"),
                            Address = "Nasr City, Cairo",
                            DateOfBirth = new DateTime(2002, 5, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyPhone = "01012345678",
                            NationalId = "30101234567891"
                        },
                        new
                        {
                            StudentID = new Guid("22222222-2222-2222-2222-222222222222"),
                            Address = "Maadi, Cairo",
                            DateOfBirth = new DateTime(2001, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyPhone = "01123456789",
                            NationalId = "30202345678912"
                        },
                        new
                        {
                            StudentID = new Guid("33333333-3333-3333-3333-333333333333"),
                            Address = "Heliopolis, Cairo",
                            DateOfBirth = new DateTime(2003, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyPhone = "01234567890",
                            NationalId = "30303456789123"
                        },
                        new
                        {
                            StudentID = new Guid("44444444-4444-4444-4444-444444444444"),
                            Address = "New Cairo, Cairo",
                            DateOfBirth = new DateTime(2002, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyPhone = "01098765432",
                            NationalId = "30404567891234"
                        },
                        new
                        {
                            StudentID = new Guid("55555555-5555-5555-5555-555555555555"),
                            Address = "Dokki, Giza",
                            DateOfBirth = new DateTime(2001, 7, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EmergencyPhone = "01187654321",
                            NationalId = "30505678912345"
                        });
                });

            modelBuilder.Entity("task_01_ef_core_modeling_drills.Entities.TrainingTrack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.ToTable("TrainingTracks");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            InstructorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = ".NET Backend Development"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            InstructorId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Name = "Database Fundamentals"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            InstructorId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Name = "Cloud Development"
                        });
                });

            modelBuilder.Entity("task_01_ef_core_modeling_drills.Entities.Enrollment", b =>
                {
                    b.HasOne("task_01_ef_core_modeling_drills.Entities.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("task_01_ef_core_modeling_drills.Entities.TrainingTrack", "TrainingTrack")
                        .WithMany("Enrollments")
                        .HasForeignKey("TrackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("TrainingTrack");
                });

            modelBuilder.Entity("task_01_ef_core_modeling_drills.Entities.PaymentSummary", b =>
                {
                    b.HasOne("task_01_ef_core_modeling_drills.Entities.Enrollment", "Enrollment")
                        .WithOne("PaymentSummary")
                        .HasForeignKey("task_01_ef_core_modeling_drills.Entities.PaymentSummary", "EnrollmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrollment");
                });

            modelBuilder.Entity("task_01_ef_core_modeling_drills.Entities.StudentProfile", b =>
                {
                    b.HasOne("task_01_ef_core_modeling_drills.Entities.Student", null)
                        .WithOne("StudentProfile")
                        .HasForeignKey("task_01_ef_core_modeling_drills.Entities.StudentProfile", "StudentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("task_01_ef_core_modeling_drills.Entities.TrainingTrack", b =>
                {
                    b.HasOne("task_01_ef_core_modeling_drills.Entities.Instructor", "Instructor")
                        .WithMany("TrainingTracks")
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("task_01_ef_core_modeling_drills.Entities.Enrollment", b =>
                {
                    b.Navigation("PaymentSummary")
                        .IsRequired();
                });

            modelBuilder.Entity("task_01_ef_core_modeling_drills.Entities.Instructor", b =>
                {
                    b.Navigation("TrainingTracks");
                });

            modelBuilder.Entity("task_01_ef_core_modeling_drills.Entities.Student", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("StudentProfile")
                        .IsRequired();
                });

            modelBuilder.Entity("task_01_ef_core_modeling_drills.Entities.TrainingTrack", b =>
                {
                    b.Navigation("Enrollments");
                });
#pragma warning restore 612, 618
        }
    }
}
